const ProductCategory = [
  { id: 1, label: "Airpodes", value: "airpodes" },
  { id: 2, label: "Camera", value: "camera" },
  { id: 3, label: "Earphones", value: "earphones" },
  { id: 4, label: "Mobiles", value: "mobiles" },
  { id: 5, label: "Mouse", value: "mouse" },
  { id: 6, label: "Printers", value: "printers" },
  { id: 7, label: "Processor", value: "processor" },
  { id: 8, label: "Refrigerator", value: "refrigerator" },
  { id: 9, label: "Speakers", value: "speakers" },
  { id: 10, label: "Trimmers", value: "trimmers" },
  { id: 11, label: "Televisions", value: "televisions" },
  { id: 12, label: "Watches", value: "watches" },
  { id: 13, label: "Washing Machine", value: "washingmachine" },
  { id: 14, label: "Laptop", value: "laptops" },
  { id: 15, label: "Shirt", value: "shirt" },
  { id: 16, label: "T-Shirts", value: "tshirts" },
  { id: 17, label: "Jeans", value: "jeans" },
  { id: 18, label: "Jackets", value: "jackets" },
  { id: 19, label: "Sweaters", value: "sweaters" },
  { id: 20, label: "Dresses", value: "dresses" },
  { id: 21, label: "Sarees", value: "sarees" },
  { id: 22, label: "Curtains", value: "curtains" },
  { id: 23, label: "Bedsheets", value: "bedsheets" },
  { id: 24, label: "Pillows", value: "pillows" },
  { id: 25, label: "Sofa Covers", value: "sofacovers" },
  { id: 26, label: "Carpets", value: "carpets" },
  { id: 27, label: "Dining Table", value: "diningtable" },
  { id: 28, label: "Chairs", value: "chairs" },
  { id: 29, label: "Couches", value: "couches" },
  { id: 30, label: "Wardrobes", value: "wardrobes" },
  { id: 31, label: "Kitchenware", value: "kitchenware" },
  { id: 32, label: "Cookware", value: "cookware" },
  { id: 33, label: "Storage Boxes", value: "storageboxes" },
  { id: 34, label: "Decorative Lights", value: "decorativelights" },
  { id: 35, label: "Clocks", value: "clocks" },
  { id: 36, label: "Mirrors", value: "mirrors" },
];

export default ProductCategory;
